name: copy-image
on: workflow_dispatch
permissions:
  packages: write
  contents: read
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - uses: imjasonh/setup-crane@v0.4
      - run: |
          crane auth login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          crane copy ghcr.io/diodonfrost/exherbo-ci-rust:latest \ 
          ghcr.io/${{ github.repository_owner }}/exherbo-ci-rust:latest
